name: Deploy to Firebase for Production
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing the dependencies
      run: npm i
    - name: Next.js build
      run: npm run build
    - name: Install firebase tools
      run: sudo npm i -g firebase-tools
    - name: Deploy to Firebase
      run: |
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}